/**
 * `<game>-tiger.conf` management (rework plan AD-6): generate a conf from the
 * extension settings. It is written into the mod's config dir (`.px-toolkit/`),
 * which the Workshop upload filter always leaves out, so a published mod never
 * ships it. A conf a user keeps at the mod root is still honoured (tiger finds
 * that one by itself) and is never overwritten.
 *
 * The filename is the meta's `tiger.confName` — the single source of truth for
 * what the binary looks for. Games without a tiger have no conf to generate.
 */
import * as vscode from "vscode";
import * as fs from "fs";
import * as path from "path";
import type { PxConfig } from "../config";
import { metaFor } from "../meta";
import { migrateConfigDir } from "@px-lsp/protocol/configDir";
import { renderLoadModBlocks } from "./loadMods";

export async function generateTigerConfCommand(cfg: PxConfig): Promise<void> {
  const meta = metaFor(cfg.gameId);
  if (!meta.tiger) {
    void vscode.window.showInformationMessage(
      `Paradox Modding Toolkit: ${meta.name} has no tiger validator, so there is no conf file to generate.`
    );
    return;
  }
  if (!cfg.modPath) {
    void vscode.window.showWarningMessage(
      "Paradox Modding Toolkit: no mod folder found. Open your mod folder (the one with the mod's descriptor) as a workspace folder."
    );
    return;
  }
  const confName = meta.tiger.confName;
  const configDir = migrateConfigDir(cfg.modPath, meta);
  const confFile = path.join(configDir, confName);
  // A root conf wins for tiger's own lookup, so an existing one either place is
  // the conf in force: open it instead of writing a second one.
  const existing = [confFile, path.join(cfg.modPath, confName)].find((f) => fs.existsSync(f));
  if (existing) {
    const doc = await vscode.workspace.openTextDocument(existing);
    await vscode.window.showTextDocument(doc);
    void vscode.window.showInformationMessage(
      `Paradox Modding Toolkit: ${path.relative(cfg.modPath, existing).replace(/\\/g, "/")} already exists, opened it instead.`
    );
    return;
  }
  // Dependency mods (px.parentMods + other workspace mods) as load_mod blocks,
  // so tiger resolves their definitions instead of reporting them unknown.
  const deps = renderLoadModBlocks(meta.descriptor, cfg.parentPaths, cfg.modPath);
  const relConf = `${path.basename(configDir)}/${confName}`;
  const content = [
    `# Generated by the Paradox Modding Toolkit extension; see https://github.com/${meta.tiger.repoSlug}/blob/main/filter.md`,
    `# Run tiger by hand with: ${meta.tiger.binaryName} --config ${relConf} <mod folder>`,
    "languages = {",
    `\tcheck = "${cfg.locLanguage}"`,
    "}",
    "",
    ...(deps.conf !== "" ? [deps.conf.trimEnd(), ""] : []),
    "# Example filter — silence a whole report family:",
    "# filter = {",
    "#     trigger = {",
    "#         NOT = { key = missing-localization }",
    "#     }",
    "# }",
    "",
  ].join("\n");
  fs.mkdirSync(configDir, { recursive: true });
  fs.writeFileSync(confFile, content, "utf8");
  const doc = await vscode.workspace.openTextDocument(confFile);
  await vscode.window.showTextDocument(doc);
  const depNote = deps.loaded.length > 0 ? `, ${deps.loaded.length} dependency mod(s) declared` : "";
  void vscode.window.showInformationMessage(
    `Paradox Modding Toolkit: generated ${relConf} (loc checks limited to ${cfg.locLanguage}${depNote}).`
  );
}
