/**
 * ck3-tiger.conf management (rework plan AD-6): generate a conf in the mod
 * root from the extension settings. An existing conf is never overwritten.
 */
import * as vscode from "vscode";
import * as fs from "fs";
import * as path from "path";
import type { PxConfig } from "../config";
import { tigerFlavorFor } from "../tigerDownload";

export async function generateTigerConfCommand(cfg: PxConfig): Promise<void> {
  if (!cfg.modPath) {
    void vscode.window.showWarningMessage("Paradox Toolkit: no mod folder (open one or set px.modPath).");
    return;
  }
  const confName = `${tigerFlavorFor(cfg.gameId).prefix}.conf`;
  const confFile = path.join(cfg.modPath, confName);
  if (fs.existsSync(confFile)) {
    const doc = await vscode.workspace.openTextDocument(confFile);
    await vscode.window.showTextDocument(doc);
    void vscode.window.showInformationMessage(
      `Paradox Toolkit: ${confName} already exists — opened it instead.`
    );
    return;
  }
  const content = [
    "# Generated by the Paradox Toolkit extension; see https://github.com/amtep/tiger/blob/main/filter.md",
    "languages = {",
    `\tcheck = "${cfg.locLanguage}"`,
    "}",
    "",
    "# Example filter — silence a whole report family:",
    "# filter = {",
    "#     trigger = {",
    "#         NOT = { key = missing-localization }",
    "#     }",
    "# }",
    "",
  ].join("\n");
  fs.writeFileSync(confFile, content, "utf8");
  const doc = await vscode.workspace.openTextDocument(confFile);
  await vscode.window.showTextDocument(doc);
  void vscode.window.showInformationMessage(
    `Paradox Toolkit: generated ${confName} (loc checks limited to ${cfg.locLanguage}).`
  );
}
