/**
 * The webview tab icons: media/tab-<name>-{light,dark}.svg, generated by
 * scripts/gen-tab-icons.ts from the same Lucide glyph the Tools section row
 * uses, so a tab and the row that opens it read as one thing.
 *
 * The extension URI is set once at activation: the panels that need a tab
 * icon are opened from many places, and threading the context through every
 * `show()` for a file path is not worth the signatures.
 */
import * as vscode from "vscode";

export type TabIconName =
  | "gui-editor"
  | "flag-builder"
  | "event-graph"
  | "gui-tree"
  | "event-sim"
  | "workshop"
  | "bbcode-preview"
  | "examples-wiki"
  | "trait-creator"
  | "wiki"
  | "credits";

let extensionUri: vscode.Uri | undefined;

export function setTabIconRoot(uri: vscode.Uri): void {
  extensionUri = uri;
}

export function tabIcon(name: TabIconName): { light: vscode.Uri; dark: vscode.Uri } | undefined {
  if (!extensionUri) return undefined;
  return {
    light: vscode.Uri.joinPath(extensionUri, "media", `tab-${name}-light.svg`),
    dark: vscode.Uri.joinPath(extensionUri, "media", `tab-${name}-dark.svg`),
  };
}
