/**
 * Generate the GAME-SIDE localization for a `px.calendar` display calendar:
 * the era-math datafunction keys plus the `localization/replace/` overrides
 * of the engine's date-format and month-name keys. This is the mirror image
 * of calendar.ts: that file teaches the EDITOR the mapping, this one writes
 * the mapping into the mod so the GAME displays it (the AGoT/LotR technique).
 *
 * Pure logic, no `vscode` imports; the extension command writes the returned
 * files (adding the BOM) and per-game key names come in via `CalendarLocSpec`
 * from the GameProfile, so no game knowledge lives here.
 */
import type { CalendarSetting } from "./calendar";
import { monthsOf } from "./calendar";

/**
 * The loc keys a game formats dates through, verified against the game's
 * binary/files. Lives in the GameProfile (`games/<id>/meta.ts`); a profile
 * without one does not support generation.
 */
export interface CalendarLocSpec {
  /**
   * Vanilla date-format keys to override in `localization/replace/`, mapped
   * to their format template. `{year}` and `{era}` mark where the generated
   * era-math key references go; everything else is kept verbatim (the
   * vanilla `$DAY$`/`$MONTH$` parameters).
   */
  dateFormats: Record<string, string>;
  /**
   * Engine month-name loc keys, first month first: [longKey, shortKey].
   * Overridden only when the calendar declares custom months, and only when
   * it declares exactly as many months as the engine has.
   */
  monthKeys?: [string, string][];
}

/** One file the generator wants written, path relative to the mod root. */
export interface GeneratedLocFile {
  /** Forward slashes; the writer joins it onto the mod root. */
  relPath: string;
  /** Content without BOM; the writer prepends it. */
  content: string;
}

export interface CalendarLocResult {
  files: GeneratedLocFile[];
  /** Facts the modder should know after generating (limits, follow-ups). */
  notes: string[];
}

/** Keys the generated files define; exported so tests and docs stay in sync. */
export const CAL_YEAR_KEY = "PX_CAL_YEAR";
export const CAL_ERA_KEY = "PX_CAL_ERA";

/** Era labels sit inside '...' CString literals; a quote would break the
 * datafunction silently, which is exactly the failure class we exist to
 * prevent. */
function cstring(label: string): string {
  return label.replace(/'/g, "");
}

/**
 * `[Select_int32(...)]` era math for the year, mirroring
 * calendar.ts `displayYear`: y >= epoch shows as y - (epoch - 1), below as
 * epoch - y. A single-era calendar (no `before`) clamps to 1 instead, so
 * pre-epoch years never display as 0 or negative.
 */
function yearExpr(cal: CalendarSetting): string {
  const year = "'(int32)$YEAR|q$'";
  const toAfter = `Subtract_int32( ${year}, '(int32)${cal.epoch - 1}' )`;
  if (!cal.before) return `[Max_int32( ${toAfter}, '(int32)1' )]`;
  const toBefore = `Subtract_int32( '(int32)${cal.epoch}', ${year} )`;
  return `[Select_int32( GreaterThanOrEqualTo_int32( ${year}, '(int32)${cal.epoch}' ), ${toAfter}, ${toBefore} )]`;
}

function eraExpr(cal: CalendarSetting): string {
  if (!cal.before) return cal.after;
  return (
    `[Select_CString( GreaterThanOrEqualTo_int32( '(int32)$YEAR|q$', '(int32)${cal.epoch}' ), ` +
    `'${cstring(cal.after)}', '${cstring(cal.before)}' )]`
  );
}

function locFile(lang: string, lines: string[]): string {
  return [`l_${lang}:`, ...lines, ""].join("\n");
}

/**
 * The two files implementing the calendar in game:
 *
 * - `localization/<lang>/px_calendar_l_<lang>.yml` - the era-math keys
 *   (new keys, so NOT in replace/).
 * - `localization/replace/<lang>/px_calendar_dates_l_<lang>.yml` - the
 *   vanilla date-format overrides routing `$YEAR$` through them, plus the
 *   engine month-name overrides when the calendar has custom months.
 *
 * Deterministic filenames: regenerating after a `px.calendar` change
 * overwrites the same two files.
 */
export function generateCalendarLoc(
  cal: CalendarSetting,
  spec: CalendarLocSpec,
  lang: string
): CalendarLocResult {
  const notes: string[] = [];
  const header = [
    " # Generated by 'Paradox: Generate Calendar Localization' from the px.calendar",
    " # setting. Edit px.calendar and regenerate instead of editing by hand.",
  ];

  const eraDoc = cal.before
    ? ` # Script year >= ${cal.epoch} shows as (year - ${cal.epoch - 1}) ${cal.after}; below as (${cal.epoch} - year) ${cal.before}.`
    : ` # Script year >= ${cal.epoch} shows as (year - ${cal.epoch - 1}) ${cal.after}; earlier years clamp to 1.`;
  const mathLines = [
    ...header,
    eraDoc,
    ` ${CAL_YEAR_KEY}:0 "${yearExpr(cal)}"`,
    ` ${CAL_ERA_KEY}:0 "${eraExpr(cal)}"`,
  ];

  const overrideLines = [
    ...header,
    " # Overrides of the engine's date-format keys: same formats as vanilla, with",
    ` # the raw $YEAR$ routed through ${CAL_YEAR_KEY}/${CAL_ERA_KEY}.`,
  ];
  for (const [key, format] of Object.entries(spec.dateFormats)) {
    const value = format.replace("{year}", `$${CAL_YEAR_KEY}$`).replace("{era}", `$${CAL_ERA_KEY}$`);
    overrideLines.push(` ${key}:0 "${value}"`);
  }

  if (cal.months) {
    const months = monthsOf(cal);
    if (!spec.monthKeys) {
      notes.push("This game's month-name keys are not mapped yet; custom month names were not generated.");
    } else if (months.length !== spec.monthKeys.length) {
      notes.push(
        `The engine has exactly ${spec.monthKeys.length} months; your calendar declares ${months.length}, ` +
          "so month names were not generated (the month count itself cannot be modded)."
      );
    } else {
      overrideLines.push(" # Engine month names (long and abbreviated forms both get the custom name).");
      months.forEach((m, i) => {
        const [long, short] = spec.monthKeys![i];
        overrideLines.push(` ${long}:0 "${m.name.replace(/"/g, '\\"')}"`);
        if (short !== long) overrideLines.push(` ${short}:0 "${m.name.replace(/"/g, '\\"')}"`);
      });
      notes.push(
        "Month day counts are engine-fixed (31/28/31...); custom day counts only affect the editor's display."
      );
    }
  }

  notes.push(
    `Generated for '${lang}' only; other languages the mod ships need the same overrides in their replace folder.`
  );

  return {
    files: [
      { relPath: `localization/${lang}/px_calendar_l_${lang}.yml`, content: locFile(lang, mathLines) },
      {
        relPath: `localization/replace/${lang}/px_calendar_dates_l_${lang}.yml`,
        content: locFile(lang, overrideLines),
      },
    ],
    notes,
  };
}
