/**
 * The webview tab icons (packages/vscode/media/tab-*.svg), generated from the
 * same Lucide paths the Tools section and the webviews draw (shared/icons.ts),
 * so a tab, its Tools row and its in-page buttons are one glyph. The only
 * difference allowed is colour: the tab carries the brand accent.
 *
 * Run: npx esbuild scripts/gen-tab-icons.ts --bundle --platform=node \
 *        --outfile=dist/gen-tab-icons.cjs && node dist/gen-tab-icons.cjs
 */
import * as fs from "fs";
import * as path from "path";
import { PATHS, type IconName } from "../packages/vscode/src/webviews/shared/icons";

/** Tab name -> the icon its Tools row uses (dashboard/actions.ts). */
export const TAB_ICONS: Record<string, IconName> = {
  "gui-editor": "layoutTemplate",
  "flag-builder": "flag",
  "event-graph": "waypoints",
  "gui-tree": "listTree",
  "event-sim": "flaskConical",
  "examples-wiki": "bookOpen",
  // The Create-group row's glyph: ck3Meta.creators names "globe" for culture.
  "culture-creator": "globe",
  wiki: "library",
  credits: "heart",
  workshop: "cloudUpload",
  "bbcode-preview": "eye",
};

const COLORS = { dark: "#A78BFA", light: "#6D4FC2" };
const outDir = path.join(__dirname, "..", "packages", "vscode", "media");
for (const [tab, icon] of Object.entries(TAB_ICONS)) {
  for (const [theme, color] of Object.entries(COLORS)) {
    const svg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="${color}" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">\n<!-- Generated by scripts/gen-tab-icons.ts from shared/icons.ts "${icon}": do not edit. -->\n${PATHS[icon]}\n</svg>\n`;
    fs.writeFileSync(path.join(outDir, `tab-${tab}-${theme}.svg`), svg);
  }
}
console.log(`wrote ${Object.keys(TAB_ICONS).length * 2} tab icons to ${outDir}`);
