/**
 * The codicon glyphs the Examples Wiki draws, generated from @vscode/codicons
 * into packages/vscode/src/webviews/exampleWiki/codiconGlyphs.ts.
 *
 * A webview cannot reach VS Code's codicon font, so the wiki inlines the paths
 * instead: the same picture the hover badge and the completion row draw, from
 * the same kind table (protocol/kinds.ts). Only the codicons that table names
 * are emitted, so the bundle carries no unused glyph.
 *
 * Codicon aliases share one codepoint and ship as ONE svg file, named after the
 * first name in the mapping entry. `symbol-value` and the other five aliases the
 * table uses resolve through mapping.json rather than existing as files.
 *
 * Run: npx esbuild scripts/gen-codicon-glyphs.ts --bundle --platform=node \
 *        --outfile=dist/gen-codicon-glyphs.cjs && node dist/gen-codicon-glyphs.cjs
 * (then delete the .cjs - everything in dist/ ships).
 */
import { execSync } from "child_process";
import * as fs from "fs";
import * as path from "path";
import { DEFAULT_KIND_STYLE, kindStyle, mappedKinds } from "../packages/protocol/src/kinds";

const pkgDir = path.join(__dirname, "..", "node_modules", "@vscode", "codicons");
const iconsDir = path.join(pkgDir, "src", "icons");
const version = JSON.parse(fs.readFileSync(path.join(pkgDir, "package.json"), "utf8")).version;

/** codepoint -> every name for it; the first name owns the svg file. */
const mapping: Record<string, string[]> = JSON.parse(
  fs.readFileSync(path.join(pkgDir, "src", "template", "mapping.json"), "utf8")
);

function fileFor(name: string): string {
  const direct = path.join(iconsDir, `${name}.svg`);
  if (fs.existsSync(direct)) return direct;
  for (const names of Object.values(mapping)) {
    if (!names.includes(name)) continue;
    // Which alias of the codepoint owns the file is the package's business, so
    // take whichever one is on disk: they are one picture by definition.
    for (const alias of names) {
      const file = path.join(iconsDir, `${alias}.svg`);
      if (fs.existsSync(file)) return file;
    }
  }
  throw new Error(`no codicon named ${name}`);
}

/** The drawing inside the 16x16 viewBox, without the wrapper the app writes. */
function inner(file: string): string {
  const svg = fs.readFileSync(file, "utf8").trim();
  const body = svg.replace(/^<svg[^>]*>/, "").replace(/<\/svg>$/, "");
  if (body === svg) throw new Error(`unexpected svg shape in ${file}`);
  return body.trim();
}

const names = [...new Set([...mappedKinds().map((k) => kindStyle(k).codicon), DEFAULT_KIND_STYLE.codicon])];
names.sort();

const rows = names.map((name) => `  "${name}": '${inner(fileFor(name))}',`).join("\n");
const out = `/**
 * Generated by scripts/gen-codicon-glyphs.ts from @vscode/codicons ${version}
 * (icons CC-BY-4.0, see THIRD-PARTY-NOTICES.md): do not edit.
 *
 * The drawing inside a 16x16 viewBox for every codicon protocol/kinds.ts names.
 * Data only: the app wraps it in the <svg> element and paints it with the
 * kind's colour.
 */
export const CODICON_PATHS: Record<string, string> = {
${rows}
};
`;

const outFile = path.join(
  __dirname,
  "..",
  "packages",
  "vscode",
  "src",
  "webviews",
  "exampleWiki",
  "codiconGlyphs.ts"
);
fs.writeFileSync(outFile, out);
// The output is committed, so it has to survive `pnpm run lint`.
execSync(`npx prettier --write "${outFile}"`, { stdio: "inherit" });
console.log(`wrote ${names.length} codicon glyphs to ${outFile}`);
